// check isloggedin
GET {{base}}/auth


###
// login
POST {{base}}/auth/login
Content-Type: application/json

{
    "username":"guest",
    "password":"123456"
}


###
// register
POST {{base}}/auth/register
Content-Type: application/json

{
    "username":"novi",
    "gender":"female",
    "email":"novi@gmail.com",
    "password":"123456",
    "confirm_password":"123456"
}


###
// refresh token require refresh token from cookie
POST {{base}}/auth/refresh
Authorization: Bearer {{token}}


###
// change user password
POST {{base}}/auth/change_password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "_id": "6309004712cdf2e74d1e4577",
    "password_old": "123456",
    "password_new": "1234567",
    "password_new_confirm": "1234567"
}