// check isloggedin
GET {{base}}/auth

###
// login
POST {{base}}/auth/login
Content-Type: application/json

{
    "username":"novi",
    "password":"1234567"
}

###
// register
POST {{base}}/auth/register
Content-Type: application/json

{
    "username":"novi",
    "gender":"female",
    "email":"novi@gmail.com",
    "password":"123456",
    "confirm_password":"123456"
}
###

GET {{base}}/auth

###

POST {{base}}/auth/refresh

###
// register
POST {{base}}/auth/change_password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "_id": "6309004712cdf2e74d1e4577",
    "password_old": "123456",
    "password_new": "1234567",
    "password_new_confirm": "1234567"
}