// get all comments
GET {{base}}/comment

###

// add new comment
POST {{base}}/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "senderId":"630c7ed3a60269f120d38bee",
    "postId":"63130708a89e968bfba989f8",
    "msg":"try comment one"
}

###
// get comment by post id
GET {{base}}/comment/63130708a89e968bfba989f8
Authorization: Bearer {{token}}

###
// delete comment by id 6314d5837ee5871961ff28a1
DELETE {{base}}/comment/6316422a0621b18d0eb8ea5d
Authorization: Bearer {{token}}

###
// toggle like comment
POST {{base}}/comment/631f0185f405bee5526d4360
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId":"631e30a632dd6b172834e83c"
}
