###
// get all post
GET {{base}}/post

###
// get post by post id
GET {{base}}/post/6316442a0621b18d0eb8ea8c

###
// get post by user id
GET {{base}}/post/user/63137937ba39d74d36e1cc8d

###
// create new post
POST {{base}}/post
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId":"63049de40a8779bd2b154792",
    "uniqueId": "kjhbdsbfdsbfbdsfkhdfjs",
    "caption":"im testing upload multiple images",
    "hashtag":"multiple image"
}

###

// delete post by id
DELETE {{base}}/post/631890ffd5e84f6d304a0d09
Authorization: Bearer {{token}}

###
// toggle like and unlike post
PUT {{base}}/post/like
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postId":"63137ad474a8d32af3a56771",
    "userId":"63137937ba39d74d36e1cc8d"
}

###
// toggle save and unsave post
PUT {{base}}/post/save
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postId":"6314d5837ee5871961ff28a1",
    "userId":"63137937ba39d74d36e1cc8d"
}
