###
// get all post
GET {{base}}/post

###
// create new post
POST {{base}}/post
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId":"63049de40a8779bd2b154792",
    "uniqueId": "kjhbdsbfdsbfbdsfkhdfjs",
    "caption":"im testing upload multiple images",
    "hashtag":"multiple image"
}

###

// delete post by id
DELETE {{base}}/post/630cfefea60269f120d38c9a
Authorization: Bearer {{token}}

###
// like or unlike post
POST {{base}}/post/like
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postId":"63137ad474a8d32af3a56771",
    "userId":"63137937ba39d74d36e1cc8d"
}
